/**
 * GENERATED FILE — do not edit by hand.
 *
 * Imported from the course catalog on resourceroomnc.com by
 * `node scripts/import-wordpress.mjs`. Re-running the script overwrites this
 * file wholesale, so make content changes in WordPress and re-import.
 *
 * Source of truth: https://resourceroomnc.com/wp-json/wp/v2 (courses)
 */

export type Course = {
  slug: string;
  name: string;
  /** The catalog group this course is listed under. */
  group: string;
  /** Grade band pulled off the course title, where it states one. */
  grades: string | null;
  summary: string;
  /** Course description, one entry per paragraph. */
  body: string[];
  /** Published rate. Null where the live site quotes on consultation. */
  price: { low: number; high: number } | null;
  image: string | null;
  imageAlt: string;
  /** The URL this lived at on WordPress, used to build redirects. */
  legacyPath: string;
};

export const courses: Course[] = [
  {
    slug: `summer-early-reading-instruction`,
    name: `Early Reading Instruction`,
    group: `Emerging Learners`,
    grades: null,
    summary: `Join us for private, individualized early childhood literacy instruction with a focus on phonics.`,
    price: null,
    image: `/images/courses/summer-early-reading-instruction.jpg`,
    imageAlt: `Early Reading Instruction`,
    legacyPath: `/product/summer-early-reading-instruction/`,
    body: [
      `Welcome to the Resource Room Learning Center’s Early Reading Instruction Program`,
      `Introduction to Reading for Kindergarten and First Grade Students`,
      `We invite you to enroll your child in our specialized early childhood literacy program, focused on the foundational elements of phonics. At the Resource Room Learning Center, we are committed to providing individualized and private instruction tailored to the unique learning style of each young reader.`,
      `Enhance Your Child’s Literacy Skills with Our Phonics-Based Approach`,
      `Our program is designed to guide emerging readers in developing phonetic awareness, a critical skill for early literacy. We focus on the mastery of vowel and consonant sounds, as well as the blending of these sounds, to form the building blocks of reading.`,
      `A Comprehensive 10-Week Early Reading Program`,
      `Prepare your child to excel in reading with our 10-week program, meticulously crafted for young learners. This program is aimed at instilling confidence and proficiency in reading from an early age.`,
      `Contact Us for Further Information and Free Consultation`,
      `We welcome your inquiries and interest in our program. Please feel free to call, text, or contact us through our website. Our team is available to answer any questions and to schedule a complimentary consultation to discuss your child’s reading journey.`,
      `Exploring the Components of Early Reading Instruction`,
      `Phonics Instruction`,
      `Phonics is an integral method in teaching young children the relationship between letters and sounds, forming the foundation for word recognition and decoding skills necessary for reading fluency and comprehension.`,
      `Word Recognition Enhancement`,
      `Our instruction in phonics will improve your child’s ability to recognize and identify words, enhancing their reading skills and allowing them to access a broader range of texts.`,
      `Development of Spelling and Writing Abilities`,
      `The program also focuses on spelling and writing, enabling children to understand sound-letter correspondences and apply this knowledge in their spelling, leading to accurate and independent writing.`,
      `Vocabulary Expansion`,
      `A significant aspect of our program is aiding children in the development of their vocabulary. As they learn phonetic patterns, they can decode unfamiliar words, thereby enriching their language skills.`,
      `Advancement in Reading Comprehension`,
      `Phonics instruction is a vital step towards achieving reading comprehension. It facilitates a better understanding of text by enabling children to focus more on the meaning rather than struggling with word decoding.`,
      `Promotion of Independent Reading`,
      `Our early phonics instruction empowers children to become autonomous readers, confident in exploring texts independently, fostering a lifelong love for reading and learning.`,
      `At the Resource Room Learning Center, we are dedicated to laying a strong foundation for successful reading and language development in young children. Through our program, we equip them with the essential skills to become proficient and confident readers.`,
    ],
  },
  {
    slug: `lego-exploration`,
    name: `Lego Exploration`,
    group: `Emerging Learners`,
    grades: null,
    summary: `Lego Bricks are a child’s gateway to imagination and learning.`,
    price: null,
    image: `/images/courses/lego-exploration.jpg`,
    imageAlt: `Lego Exploration`,
    legacyPath: `/product/lego-exploration/`,
    body: [
      `Course Description`,
      `Lego Bricks are a child’s gateway to imagination and learning.`,
      `Our themed and guided Lego hours allow children to explore their creativity`,
      `alongside their peers.`,
      `Students will build, experiment, and explore various building methods to create a marvel of engineering. Each build is structured and themed to provide an educational and fun experience.`,
      `Sorry parents – this is a child-only drop-off program. You will have to find some other way to occupy an hour or two while they are building their creations.`,
      `the LEGO spike program students will be introduced to the basics of block coding and learn creative problem-solving. Themed builds will pose certain challenges to students for which they will have to design and code their LEGO robot to overcome. LEGO exploration is open to students aged 6-10 (Grades K-6)`,
      `Schedule`,
      `Date Time`,
      `February 17th, 2023 6:00 PM - 7:30 PM`,
      `March 3rd, 2023 6:00 PM - 7:30 PM`,
      `March 10th, 2023 6:00 PM - 7:30 PM`,
      `March 17th, 2023 6:00 PM - 7:30 PM`,
      `March 24th, 2023 6:00 PM - 7:30 PM`,
    ],
  },
  {
    slug: `minecraft-education`,
    name: `Minecraft Education`,
    group: `Emerging Learners`,
    grades: null,
    summary: `Minecraft has a plethora of features where students can experiment with levers, switches, and electrical circuits aka redstone. Students will be able to create farming systems or harness energy to create water cycles and renewable energy. Minecraft also enables a space for students to visualize and investigate different situations where they can create solutions which helps them to develop critical and spatial thinking.`,
    price: null,
    image: `/images/courses/minecraft-education.jpg`,
    imageAlt: `minecraft`,
    legacyPath: `/product/minecraft-education/`,
    body: [
      `About the Course`,
      `Minecraft has a plethora of features where students can experiment with levers, switches, and electrical circuits aka redstone. Students will be able to create farming systems or harness energy to create water cycles and renewable energy. Minecraft also enables a space for students to visualize and investigate different situations where they can create solutions which helps them to develop critical and spatial thinking.`,
      `This 5 week course will help build skills like collaboration, creative problem-solving, communication , and systems thinking.`,
      `Schedule`,
      `Date Time`,
      `January 13 6 P.M. - 8 P.M.`,
      `January 20 6 P.M. - 8 P.M.`,
      `January 27 6 P.M. - 8 P.M.`,
      `February 3 6 P.M. - 8 P.M.`,
      `February 10 6 P.M. - 8 P.M.`,
    ],
  },
  {
    slug: `ms-sams-new-2-numbers`,
    name: `Ms. Sam’s New 2 Numbers`,
    group: `Emerging Learners`,
    grades: null,
    summary: `For our youngest minds. This class is for 3 and 4 year old students.`,
    price: { low: 45, high: 45 },
    image: `/images/courses/ms-sams-new-2-numbers.jpg`,
    imageAlt: `Ms. Sam’s New 2 Numbers`,
    legacyPath: `/product/ms-sams-new-2-numbers/`,
    body: [
      `Course Description`,
      `For our youngest minds. This class is for 3 and 4 year old students.`,
      `Ms. Sam’s New 2 Numbers provides an introduction to the foundational principles of counting, sorting, stacking, adding, and subtracting. Through our themed lessons, students will also be introduced to concepts such as patterns, sequencing, shapes, classifying objects, and understanding spatial awareness.`,
      `This 45-minute class is for emerging minds only!`,
      `Join Ms. Sam as she uses themed, structured, and standards-aligned lessons to introduce basic mathematical concepts in a fun and engaging classroom environment. There is no commitment required, classes can be booked by the session. Discounts are available for multiple bookings. This type of approach allows for greater flexibility for busy parents or those with fluctuating schedules.`,
    ],
  },
  {
    slug: `story-stations`,
    name: `Story Stations +`,
    group: `Emerging Learners`,
    grades: null,
    summary: `This is not your traditional story time – it is so much more.`,
    price: { low: 45, high: 45 },
    image: `/images/courses/story-stations.jpg`,
    imageAlt: `Emerging Learners Programs`,
    legacyPath: `/product/story-stations/`,
    body: [
      `Course Description`,
      `This is not your traditional story time – it is so much more.`,
      `Our emerging readers will join us for an immersive and imaginative 75 minute adventure.`,
      `During story stations plus – children will join in a story time reading followed by a hands-on activity that accompanies the theme of the story of the day.`,
      `Not only will emerging learners build foundational literacy skills, but will also follow up each story with an engaging activity.`,
      `Our structured story hours include meaningful time for children to learn and play together while, at the same time, bonding and socializing with their peers.`,
      `Led by Ms. Sam, each story becomes a learning adventure to play, explore, and develop foundational skills.`,
    ],
  },
  {
    slug: `lego-brikq`,
    name: `Lego Robotics using BricQ`,
    group: `LEGO Robotics`,
    grades: null,
    summary: `This program offers students the opportunity to learn about and explore kinetic forces through hands-on experiences. Students will build out LEGO designs that will allow them to learn about forces such as gravity, friction, propulsion & more through play. Each class will engage students with hands-on activities as well as guided lessons to develop their understanding of the physical world.`,
    price: null,
    image: `/images/courses/lego-brikq.jpg`,
    imageAlt: `Lego BrikQ`,
    legacyPath: `/product/lego-brikq/`,
    body: [
      `The LEGO® BricQ program is an engaging and innovative approach to teaching and learning STEM concepts, primarily aimed at students in educational settings. This program utilizes LEGO® bricks, a universally recognized and beloved building tool, to introduce and reinforce key principles in science, technology, engineering, and mathematics. Here’s a more detailed description:`,
      `Key Features of the LEGO BricQ Program:`,
      `Hands-On Learning: The LEGO BricQ program emphasizes tactile, hands-on experiences. Students use LEGO® bricks to build models and conduct experiments, making abstract STEM concepts more tangible and understandable.`,
      `STEM Integration: The program seamlessly integrates various STEM disciplines. For instance, while constructing a model, students might learn about engineering principles, explore mathematical ratios, or understand scientific concepts like forces and motion.`,
      `Encourages Creativity and Problem-Solving: The LEGO BricQ program fosters creativity as students design and build their own models. It also enhances problem-solving skills, as students must figure out how to construct stable and functional structures using the bricks.`,
      `Collaborative Learning: Many LEGO BricQ activities are designed for group work, promoting teamwork and communication skills. Students learn to collaborate, share ideas, and work together to complete projects.`,
      `Adaptable for Various Age Groups: The program can be tailored to suit different educational levels. Younger students might engage in more basic building projects, while older students tackle more complex designs and concepts.`,
      `Curriculum Support: The LEGO BricQ program often comes with curriculum resources, lesson plans, and teacher guides, making it easy to integrate into existing school curriculums.`,
      `Real-World Applications: The program frequently connects the projects to real-world scenarios, helping students understand how STEM concepts apply outside the classroom.`,
      `Example Projects and Activities:`,
      `Simple Machines: Students might build levers, pulleys, or gears with LEGO® bricks to understand basic mechanical principles.`,
      `Physics Experiments: Models could be used to demonstrate principles of force, motion, energy, and balance.`,
      `Mathematical Concepts: LEGO® bricks are excellent for visualizing fractions, ratios, geometry, and other mathematical ideas.`,
      `Educational Benefits:`,
      `Engagement: The use of LEGO® bricks in education is highly engaging for students, often increasing their interest and participation in STEM subjects.`,
      `Understanding and Retention: The tactile and visual nature of building with LEGO® bricks can enhance understanding and retention of complex concepts.`,
      `Skill Development: Beyond STEM skills, the LEGO BricQ program aids in the development of fine motor skills, spatial awareness, and creative thinking.`,
      `The LEGO BricQ program represents a dynamic and interactive way to bring STEM education to life, leveraging the familiarity and appeal of LEGO® bricks to create a rich educational experience.`,
    ],
  },
  {
    slug: `lego-spike`,
    name: `Lego Spike`,
    group: `LEGO Robotics`,
    grades: null,
    summary: `Lego Bricks are a child’s gateway to imagination and learning. Click on request a consultation and see if this is the right program for your child!`,
    price: null,
    image: `/images/courses/lego-spike.jpg`,
    imageAlt: `Lego Spike`,
    legacyPath: `/product/lego-spike/`,
    body: [
      `Course Description`,
      `Lego Bricks are a child’s gateway to imagination and learning.`,
      `Our themed and guided Lego hours allow children to explore their creativity alongside their peers.`,
      `Students will build, experiment, and explore various building methods to create a marvel of engineering. Each build is structured and themed to provide an educational and fun experience.`,
      `Sorry parents – this is a child-only drop-off program. You will have to find some other way to occupy an hour or two while they are building their creations.`,
      `Using the LEGO spike program students will be introduced to the basics of block coding and learn creative problem-solving. Themed builds will pose certain challenges to students for which they will have to design and code their LEGO robot to overcome. LEGO exploration is open to students aged 6-10 (Grades K-6)`,
    ],
  },
  {
    slug: `crafty-learning`,
    name: `Crafty Learning`,
    group: `STEAM Programs`,
    grades: null,
    summary: `During this 3-Hour Drop Off Program, students will engage in themed arts and crafts, STEAM activities, and structured playtime`,
    price: { low: 79, high: 79 },
    image: `/images/courses/crafty-learning.jpg`,
    imageAlt: `Crafty Learning`,
    legacyPath: `/product/crafty-learning/`,
    body: [
      `Course Description`,
      `During this 3-Hour Drop Off Program, students will engage in themed arts and crafts, STEAM activities, and structured playtime.`,
      `This program is offered two times per week and can be booked by the session – no long term commitment required; however, you must have reserved a space prior to drop off.`,
      `Each lesson will explore a new theme that will help them develop problem solving and critical thinking skills, while helping to foster socialization and team building in a structured learning environment.`,
    ],
  },
  {
    slug: `discovery-of-3d-design-using-tinkercad-grades-3-5`,
    name: `Discovery of 3D Design Using Tinkercad (Grades 3-5)`,
    group: `STEAM Programs`,
    grades: `Grades 3-5`,
    summary: `Young learners answer the question “How does 3D Printing work?” Students will learn how to build and modify designs using concept and design software. Students will translate those designs into code, learning the fundamentals of “slicing”. Through a hands-on approach, students will create tangible products from our in-house 3D printers.`,
    price: null,
    image: `/images/courses/discovery-of-3d-design-using-tinkercad-grades-3-5.jpg`,
    imageAlt: `Discovery of 3D Design Using Tinkercad (Grades 3-5)`,
    legacyPath: `/product/discovery-of-3d-design-using-tinkercad-grades-3-5/`,
    body: [
      `Go To Schedule`,
      `Course Description`,
      `Young learners answer the question “How does 3D Printing work?” Students will learn how to build and modify designs using concept and design software. Students will translate those designs into code, learning the fundamentals of “slicing”. Through a hands-on approach, students will create tangible products from our in-house 3D printers.`,
      `Examples of Some Standards Addressed`,
      `NGSS`,
      `Science and Engineering Practices`,
      `Asking Questions and Defining Problems`,
      `Define a simple design problem that can be solved through the development of an object, tool, process, or system and includes several criteria for success and constraints on materials, time, or cost.`,
      `Crosscutting Concepts`,
      `Influence of Science, Engineering, and Technology on Society and the Natural World: People’s needs and wants change over time, as do their demands for new and improved technologies`,
      `CCSS`,
      `Math`,
      `MP.2 Reason abstractly and quantitatively.`,
      `MP.5 Use appropriate tools strategically.`,
      `CSTA`,
      `Algorithms and Programming`,
      `1B-AP-16 Take on varying roles, with teacher guidance, when collaborating with peers during the design, implementation, and review stages of program development.`,
      `21st Century Skills`,
      `21stCS_1 Critical thinking, problem-solving, reasoning, analysis, interpretation, synthesizing information.`,
      `21stCS_11 Scientific literacy and reasoning, the scientific method.`,
      `‍`,
      `Schedule`,
      `Program Date Time Lesson`,
      `3D Printing: 3-5 Session 1 January 13, 2023 6:00PM- 8:00PM Designing Tools/ Making a Signature`,
      `3D Printing: 3-5 Session 2 January 20, 2023 6:00PM- 8:00PM Modeling`,
      `3D Printing: 3-5 Session 3 January 27, 2023 6:00PM- 8:00PM Modifying and Design/ Make a Stamp`,
      `3D Printing: 3-5 Session 4 February 3, 2023 6:00PM- 8:00PM Mirroring/ 3D Printer`,
      `3D Printing: 3-5 Session 5 February 10, 2023 6:00PM- 8:00PM CAD Application/ Prepare for Print`,
      `3D Printing: 3-5 Session 6 February 17, 2023 6:00PM- 8:00PM Test and Reflect`,
      `‍`,
    ],
  },
  {
    slug: `discovery-of-unmanned-aviation-grades-3-5`,
    name: `Discovery of Drones! Booking NOW (Grades 3-5)`,
    group: `STEAM Programs`,
    grades: `Grades 3-5`,
    summary: `Young learners answer the questions “What is the history of Unmanned Aviation?” and “How do they work?” Students learn how to program drone flight through coding in the Droneblocks application.`,
    price: null,
    image: `/images/courses/discovery-of-unmanned-aviation-grades-3-5.jpg`,
    imageAlt: `Discovery of Drones! Booking NOW (Grades 3-5)`,
    legacyPath: `/product/discovery-of-unmanned-aviation-grades-3-5/`,
    body: [
      `Go To Schedule`,
      `Course Description`,
      `Students will learn to fly real drones using block based coding, Students will embark on several different missions of varying levels of complexity to fly their drones around obstacles, understand the concept of variables, and ultimately safely land their drone in a predetermined spot. No remote controls here! This is all code based and an amazing introduction into the worlds of programming and aviation.`,
      `Young learners will answer the questions “What is the history of Unmanned Aviation?” and “How do they work?” Students learn how to program drone flight through coding in the Droneblocks application.`,
      `Upcoming Schedule: Booking NOW`,
      `Program Date Time Lessons`,
      `Drones: 3-5 Session 1 Saturday, November 5, 2022 11:00 AM – 1:00 PM Introduction to Drones / Drone Safety`,
      `Drones: 3-5 Session 2 Saturday, November 12, 2022 11:00 AM – 1:00 PM What is Scratch?/ Loops, Loops, Loops`,
      `Drones: 3-5 Session 3 Saturday, November 19, 2022 11:00 AM – 1:00 PM Using Operators/ Angles and Operators`,
      `Drones: 3-5 Session 4 Saturday, December 3, 2022 11:00 AM – 1:00 PM Flying a perimeter`,
      `Drones: 3-5 Session 5 Saturday, December 10, 2022 11:00 AM – 1:00 PM Delivery Abstraction`,
      `Drones: 3-5 Session 6 Saturday, December 17, 2022 11:00 AM – 1:00 PM Understanding Range/ Time to Compete`,
      `Level One`,
      `Students will be able to explain what a drone is, its functions, and how it flies.`,
      `Students will be able to launch a basic field mission including coding the drone flight and executing the three basic motions of a drone.`,
      `Students will be able to operate a drone safely.`,
      `Students will be able to build tools to measure key factors for safe drone operation.`,
      `Students will be able to identify components of Scratch programming language.`,
      `Students will be able to construct and follow a set of sequential instructions.`,
      `Students will be able to compare the efficiency of sequences and loops in Scratch coding.`,
      `Students will be able to fly a drone to simulate the task of searching for an object in an area.`,
      `Level Two`,
      `Students will be able to simulate a real world flight by coding a flight pattern to scale.`,
      `Students will be able to convert metric units for flight into imperial units.`,
      `Students will be able to use block coding to program a drone to yaw in precise angles.`,
      `Students will be able to use block coding to fly a precise course.`,
      `Students will be able to code a drone to follow the perimeter of a complex figure.`,
      `Students will be able to define a real world area to be explored in abstract.`,
      `Students will be able to create a variable change.`,
      `Students will be able to program a flight plan for multiple deliveries.`,
      `Students will be able to test the range of the drone in 3 dimensions and record data about the effective range of the drone.`,
      `Students will be able to plot, in abstraction a flight pattern, that takes range and battery into account.`,
      `Examples of Some Standards Addressed`,
      `NGSS`,
      `Crosscutting Concepts`,
      `Influence of Science, Engineering, and Technology on Society and the Natural World:`,
      `3-5-ETS1-3 Plan and carry out fair tests in which variables are controlled and failure points are considered to identify aspects of a model or prototype that can be improved.`,
      `Disciplinary Core Ideas`,
      `ETS1.C: Optimizing the Design Solution Different solutions need to be tested in order to determine which of them best solves the problem, given the criteria and the constraints.`,
      `CCSS`,
      `Math`,
      `MP.2 Reason abstractly and quantitatively.`,
      `MP.5 Use appropriate tools strategically.`,
    ],
  },
  {
    slug: `discovery-of-robots-coding-mbot-grades-3-5`,
    name: `Discovery of Robots: Coding mBot (Grades 3-5)`,
    group: `STEAM Programs`,
    grades: `Grades 3-5`,
    summary: `Welcome to Introduction to Robots! In this course, students will go on an exploration of robotics. Through a series of activities that support inquiry and hands-on learning, students will develop an understanding of how robots function and the purposes for which they are used. Students will have the opportunity to learn how to code in the mBlockly application and program their own mBot robots. The final lessons of the course include a team competition in which students will apply the skills they’ve learned and a debate in which students consider important ethical questions around the use of robots in the modern world.`,
    price: null,
    image: `/images/courses/discovery-of-robots-coding-mbot-grades-3-5.jpg`,
    imageAlt: `Discovery of Robots: Coding mBot (Grades 3-5)`,
    legacyPath: `/product/discovery-of-robots-coding-mbot-grades-3-5/`,
    body: [
      `Go To Schedule`,
      `Course Description`,
      `Welcome to Introduction to Robots! In this course, you and your students will go on an exploration of robotics. Through a series of activities that support inquiry and hands-on learning, students will develop an understanding of how robots function and the purposes for which they are used. Students will have the opportunity to learn how to code in the mBlockly application and program their own mBot robots. The final lessons of the course include a team competition in which students will apply the skills they’ve learned and a debate in which students consider important ethical questions around the use of robots in the modern world.`,
      `Level One`,
      `Students will be able to explain what a robot is and design a robot to solve a problem.`,
      `Students will be able to name the components of the mBot and describe the function of mBots components.`,
      `Students will be able to assemble an mBot`,
      `Students will be able to explain what a sequence and algorithm are.`,
      `Students will be able to create an algorithm for someone to follow.`,
      `Students will be able to use the mBlock Blockly app to program a robot.`,
      `Level Two`,
      `Students will be able to use an increasing number of features in mBlock Blockly to program my mBot.`,
      `Students will be able to improvise and use creativity to find solutions to programming challenges.`,
      `Students will be able to explain what a line follower is.`,
      `Students will be able to design a line follower track for the mBot.`,
      `Students will be able to create, draw, and engineer different tracks for the mBot to follow.`,
      `Students will participate in a competition to display their competency in programming the mBot to complete a series of tasks.`,
      `Examples of Some Standards Addressed`,
      `NGSS`,
      `3-5-ETS1-2 Constructing explanations and designing solutions in 3–5 progresses to the use of evidence in constructing explanations that specify variables that describe and predict phenomena and in designing multiple solutions to design problems.`,
      `Science and Engineering Practices`,
      `Constructing Explanations and Designing Solutions Generate and compare multiple solutions to a problem based on how well they meet the criteria and constraints of the design problem.`,
      `Disciplinary Core Ideas`,
      `ETS1.A: Defining and Delimiting Engineering Problems`,
      `Possible solutions to a problem are limited by available materials and resources (constraints).`,
      `The success of a designed solution is determined by considering the desired features of a solution (criteria).`,
      `Different proposals for solutions can be compared on the basis of how well each one meets the specified criteria for success or how well each takes the constraints into account.`,
      `ETS1.B Developing Possible Solutions Communicating with peers about proposed solutions is an important part of the design process, and shared ideas can lead to improved designs.`,
      `Crosscutting Concepts`,
      `Influence of Science, Engineering, and Technology on Society and the Natural World Engineers improve existing technologies or develop new ones to increase their benefits, decrease known risks, and meet societal demands.`,
      `Disciplinary Core Ideas`,
      `ETS1.C: Optimizing the Design Solution`,
      `Different solutions need to be tested in order to determine which of them best solves the problem, given the criteria and the constraints.`,
      `CCSS`,
      `Math`,
      `MP.2 Reason abstractly and quantitatively.`,
      `MP.5 Use appropriate tools strategically.`,
      `3-5.OA Operations and Algebraic Thinking`,
      `‍`,
      `Schedule`,
      `Program Date Time Lessons`,
      `Robots: 3-5 Session 1 Saturday, September 10, 2022 11:00 AM- 1:00 PM What is a Robot? / Meet mBot`,
      `Robots: 3-5 Session 2 Saturday, September 17, 2022 11:00 AM- 1:00 PM Build mBot/ Coding unplugged`,
      `Robots: 3-5 Session 3 Saturday, September 24, 2022 11:00 AM- 1:00 PM Block Coding /Something New`,
      `Robots: 3-5 Session 4 Saturday, October 1, 2022 11:00 AM- 1:00 PM Line Follower / Robots at work`,
      `Robots: 3-5 Session 5 Saturday, October 8, 2022 11:00 AM- 1:00 PM What’s your plan?`,
      `Robots: 3-5 Session 6 Saturday, October 15, 2022 11:00 AM- 1:00 PM Time to Compete`,
      `‍`,
    ],
  },
  {
    slug: `exploration-of-3d-development-grades-6-8`,
    name: `Exploration of 3D Development (Grades 6-8)`,
    group: `STEAM Programs`,
    grades: `Grades 6-8`,
    summary: `Students answer questions such as “What is the Engineering Design process?” and “How can I use it to design in 3D printing for a purpose?” Students will demonstrate proficiency in using 3D Design tools from design to print out.`,
    price: null,
    image: `/images/courses/exploration-of-3d-development-grades-6-8.jpg`,
    imageAlt: `Exploration of 3D Development (Grades 6-8)`,
    legacyPath: `/product/exploration-of-3d-development-grades-6-8/`,
    body: [
      `Go To Schedule`,
      `Course Description`,
      `Students answer questions such as “What is the Engineering Design process?” and “How can I use it to design in 3D printing for a purpose?” Students will demonstrate proficiency in using 3D Design tools from design to print out.`,
      `Students will learn to expand on the fundamental coding and design principles necessary to create more complex 3D designs and products using our in-house 3D Printers.`,
      `Standards Supported in Level I & II`,
      `Disciplinary Core Ideas`,
      `ETS1.A: Defining and Delimiting Engineering Problems Possible solutions to a problem are limited by available materials and resources (constraints). The success of a designed solution is determined by considering the desired features of a solution (criteria). Different proposals for solutions can be compared on the basis of how well each one meets the specified criteria for success or how well each takes the constraints into account.`,
      `CCSS`,
      `Math`,
      `MP.2 Reason abstractly and quantitatively.`,
      `7.EE.3 Solve multi-step real-life and mathematical problems posed with positive and negative rational numbers in any form (whole numbers, fractions, and decimals), using tools strategically. Apply properties of operations to calculate with numbers in any form; convert between forms as appropriate; and assess the reasonableness of answers using mental computation and estimation strategies.`,
      `ISTE`,
      `Empowered Learner – Students understand the fundamental concepts of technology operations, demonstrate the ability to choose, use and troubleshoot current technologies and are able to transfer their knowledge to explore emerging technologies.`,
      `Creative Communicator – Students communicate clearly and express themselves creatively for a variety of purposes using the platforms, tools, styles, formats and digital media appropriate to their goals`,
      `Schedule`,
      `Program Date Time Lessons`,
      `3D Printing: 6-8 Session 1 Saturday, January 7, 2023 9:00 AM- 11:00 AM Computer-Aided Design Tool`,
      `3D Printing: 6-8 Session 2 Saturday, January 14, 2023 9:00 AM- 11:00 AM Modeling / Modifying Designs`,
      `3D Printing: 6-8 Session 3 Saturday, January 21, 2023 9:00 AM- 11:00 AM Design a Stamp/ CAD Application`,
      `3D Printing: 6-8 Session 4 Saturday, January 28, 2023 9:00 AM- 11:00 AM Design Process`,
      `3D Printing: 6-8 Session 5 Saturday, February 4, 2023 9:00 AM- 11:00 AM Slicing and Preparation for Print`,
      `3D Printing: 6-8 Session 6 Saturday, February 11, 2023 9:00 AM- 11:00 AM Printing in 3D`,
      `‍`,
    ],
  },
  {
    slug: `exploration-of-drones-coding-with-tello-grades-6-8`,
    name: `Exploration of Drones: Coding with Tello (Grades 6-8)`,
    group: `STEAM Programs`,
    grades: `Grades 6-8`,
    summary: `Students explore and apply how Unmanned Aerial Vehicles (drones) are used and function. Students will integrate algebraic thinking, programmatic knowledge, and use case scenario abstraction to control drones in Tello.`,
    price: null,
    image: `/images/courses/exploration-of-drones-coding-with-tello-grades-6-8.jpg`,
    imageAlt: `Exploration of Drones: Coding with Tello (Grades 6-8)`,
    legacyPath: `/product/exploration-of-drones-coding-with-tello-grades-6-8/`,
    body: [
      `Go To Schedule`,
      `Course Description`,
      `Students explore and apply how Unmanned Aerial Vehicles (drones) are used and function. Students will integrate algebraic thinking, programmatic knowledge, and use case scenario abstraction to control drones in Tello.`,
      `Level One`,
      `Students will be able to understand how drones are used and the laws that govern drone operation.`,
      `Students will be able to understand the ways that block coding can be used to give instructions to machines`,
      `Students will be able to compare scenarios for safe and unsafe drone operation.`,
      `Students will be able to consider the reasons why drone laws would be enacted.`,
      `Students will be able to identify components of block programming language.`,
      `Students will be able to construct and follow a set of sequential instructions.`,
      `Students will be able to compare sequences and loops in block coding.`,
      `Students will be able to compare sequences and loops in block coding.`,
      `Students will be able to understand the steps of a drone delivery and construct a simulation of a drone delivery.`,
      `Level Two`,
      `Students will be able to compare the information collected by drone sensors to information gathered by human senses`,
      `Students will be able to program drones to simulate the flight paths that would utilize sensors not currently included on the drone.`,
      `Students will be able to simulate a real world flight by coding a flight pattern to scale.`,
      `Students will be able to convert metric units for flight into imperial units.`,
      `Students will be able to compare and contrast the relationship between drones and other tools to capture information.`,
      `Students will be able to design a flight scenario to capture relevant scientific information.`,
      `Students will be able to test the range of the drone in 3 dimensions and record data about the effective range of the drone.`,
      `Students will be able to plot, in abstraction, a flight pattern that takes range and battery life into account.`,
      `Students will be able to consider current laws regulating drone usage and their impacts on public safety as usage increases.`,
      `Standards Supported in Level I & II`,
      `Crosscutting Concepts`,
      `Influence of Science, Engineering, and Technology on Society and the Natural World :`,
      `‍ The uses of technologies and limitations on their use are driven by individual or societal needs, desires, and values; by the findings of scientific research; and by differences in such factors as climate, natural resources, and economic conditions. (MS-ETS1-1).`,
      `All human activity draws on natural resources and has both short and long-term consequences, positive as well as negative, for the health of people and the natural environment. (MS-ETS1-1)`,
      `MS-ETS1-1. Define the criteria and constraints of a design problem with sufficient precision to ensure a successful solution, taking into account relevant scientific principles and potential impacts on people and the natural environment that may limit possible solutions.`,
      `Scientific and Engineering Practices`,
      `Asking questions and defining problems in grades 6–8 builds on grades K–5 experiences and progresses to specifying relationships between variables, and clarifying arguments and models.`,
      `Define a design problem that can be solved through the development of an object, tool, process or system and includes multiple criteria and constraints, including scientific knowledge that may limit possible solutions. (MS-ETS1-1)`,
      `‍`,
      `Schedule`,
      `Program Date Time Level`,
      `Drones: 6-8 Week 1 Saturday, November 13, 2021 10am-11am Level 1`,
      `Drones: 6-8 Week 2 Saturday, November 20, 2021 10am-11am Level 1`,
      `Drones: 6-8 Week 3 Saturday, December 4, 2021 10am-11am Level 1`,
      `Drones: 6-8 Week 4 Saturday, December 11, 2021 10am-11am Level 1`,
      `Drones: 6-8 Week 5 Saturday, December 18, 2021 10am-11am Level 1`,
      `Drones: 6-8 Week 6 Saturday, January 8, 2022 10am-11am Level 1`,
      `Drones: 6-8 Week 7 Saturday, January 15, 2022 10am-11am Level 2`,
      `Drones: 6-8 Week 8 Saturday, January 22, 2022 10am-11am Level 2`,
      `Drones: 6-8 Week 9 Saturday, January 29, 2022 10am-11am Level 2`,
      `Drones: 6-8 Week 10 Saturday, February 5, 2022 10am-11am Level 2`,
      `Drones: 6-8 Week 11 Saturday, February 12, 2022 10am-11am Level 2`,
      `Drones: 6-8 Week 12 Saturday, February 19, 2022 10am-11am Level 2`,
    ],
  },
  {
    slug: `exploration-of-robots-coding-mbot-for-a-purpose-grades-6-8`,
    name: `Exploration of Robots: Coding mBot for a Purpose (Grades 6-8)`,
    group: `STEAM Programs`,
    grades: `Grades 6-8`,
    summary: `Students answer questions such as, “What can a robot do?” and “How can a robot be coded to do so?” Students learn to code in the mBlockly application and program their own mBot robots for a specific purpose.`,
    price: null,
    image: `/images/courses/exploration-of-robots-coding-mbot-for-a-purpose-grades-6-8.jpg`,
    imageAlt: `Exploration of Robots: Coding mBot for a Purpose (Grades 6-8)`,
    legacyPath: `/product/exploration-of-robots-coding-mbot-for-a-purpose-grades-6-8/`,
    body: [
      `Students answer questions such as, “What can a robot do?” and “How can a robot be coded to do so?” Students learn to code in the mBlockly application and program their own mBot robots for a specific purpose.`,
      `Course Description`,
      `Level One`,
      `Students will learn what a robot is, as well as explore the ways in which robots are affecting our lives today. Students will design a robot to solve a real-life problem.`,
      `Students will explore the components and features of the mBot. Students will also assemble the mBot`,
      `Students will learn what a sequence and algorithm are. They will also participate in some coding activities that do not require a device`,
      `Students will use an increasing number of features in mBlock Blockly to program my mBot.`,
      `Students can improvise and use creativity to find solutions to programming challenges.`,
      `Examples of Some Standards Addressed`,
      `NGSS`,
      `3-5-ETS1-2 Constructing explanations and designing solutions in 3–5 progresses to the use of evidence in constructing explanations that specify variables that describe and predict phenomena and in designing multiple solutions to design problems.`,
      `Science and Engineering Practices`,
      `Constructing Explanations and Designing Solutions Generate and compare multiple solutions to a problem based on how well they meet the criteria and constraints of the design problem.`,
      `Crosscutting Concepts`,
      `Influence of Science, Engineering, and Technology on Society and the Natural World Engineers improve existing technologies or develop new ones to increase their benefits, decrease known risks, and meet societal demands.`,
      `3-5-ETS1-3 Plan and carry out fair tests in which variables are controlled and failure points are considered to identify aspects of a model or prototype that can be improved.`,
      `Disciplinary Core Ideas`,
      `ETS1.C: Optimizing the Design Solution Different solutions need to be tested in order to determine which of them best solves the problem, given the criteria and the constraints.`,
      `‍`,
    ],
  },
  {
    slug: `introduction-to-robots-what-is-a-robot-grades-k-2`,
    name: `Intro to Robots: What is a Robot? Booking NOW (Grades K-2)`,
    group: `STEAM Programs`,
    grades: `Grades K-2`,
    summary: `Early learners answer the questions “What are robots?” “How do they work?” and “What can they do?” Young learners are encouraged to combine creative thinking and intrinsic motivation using cutting-edge technology and Scratch, a free-to-use drag-and-drop creative learning environment developed by MIT Media Lab.`,
    price: null,
    image: `/images/courses/introduction-to-robots-what-is-a-robot-grades-k-2.jpg`,
    imageAlt: `STEAM students working on project`,
    legacyPath: `/product/introduction-to-robots-what-is-a-robot-grades-k-2/`,
    body: [
      `Go To Schedule`,
      `Course Description`,
      `Young learners answer the questions “What is the history of Unmanned Aviation?” and “How do they work?” Students learn how to program drone flight through coding in the Droneblocks application.`,
      `Level One`,
      `explain Colby’s robot function`,
      `write a command for Colby to follow.`,
      `create a sequence of instructions`,
      `program a robot to move to a specific point.`,
      `write a line of code.`,
      `program and debug Colby to follow my line of code.`,
      `retell stories orally.`,
      `retell stories by creating a coding sequence.`,
      `Level Two`,
      `understand sequences and give precise directions.`,
      `engage in collaborative teamwork to problem solve.`,
      `give directions and read a map.`,
      `code Colby to get from one place on a map to another.`,
      `make a creative maze for Colby.`,
      `write a sequence for Colby to go through the maze.`,
      `code a sequence.`,
      `use sequence words to describe the order of events.`,
      `explain how to add and subtract on a number line.`,
      `write a code to move Colby to find sums and differences.`,
      `Examples of Some Standards Addressed`,
      `CCSS`,
      `K-2-PS3-2 Use tools and materials provided to design and build a device that solves a specific problem or a solution to a specific problem.`,
      `K-2-ETS1-1 Ask questions, make observations, and gather information about a situation people want to change to define a simple problem that can be solved through the development of a new or improved object or tool.`,
      `Schedule`,
      `Program Date Time Level`,
      `Robots: K-2 Week 1 Saturday, November 13, 2021 11am-12pm Level 1`,
      `Robots: K-2 Week 2 Saturday, November 20, 2021 11am-12pm Level 1`,
      `Robots: K-2 Week 3 Saturday, December 4, 2021 11am-12pm Level 1`,
      `Robots: K-2 Week 4 Saturday, December 11, 2021 11am-12pm Level 1`,
      `Robots: K-2 Week 5 Saturday, December 18, 2021 11am-12pm Level 1`,
      `Robots: K-2 Week 6 Saturday, January 8, 2022 11am-12pm Level 1`,
      `Robots: K-2 Week 7 Saturday, January 15, 2022 11am-12pm Level 2`,
      `Robots: K-2 Week 8 Saturday, January 22, 2022 11am-12pm Level 2`,
      `Robots: K-2 Week 9 Saturday, January 29, 2022 11am-12pm Level 2`,
      `Robots: K-2 Week 10 Saturday, February 5, 2022 11am-12pm Level 2`,
      `Robots: K-2 Week 11 Saturday, February 12, 2022 11am-12pm Level 2`,
      `Robots: K-2 Week 12 Saturday, February 19, 2022 11am-12pm Level 2`,
    ],
  },
  {
    slug: `introduction-to-drones-take-flight-k-2nd`,
    name: `Introduction to Drones: Take Flight! (K-2nd)`,
    group: `STEAM Programs`,
    grades: `K-2nd`,
    summary: `Students will be introduced to drones. Students will experience how flight occurs and what is necessary for animals and objects to take flight.`,
    price: null,
    image: `/images/courses/introduction-to-drones-take-flight-k-2nd.jpg`,
    imageAlt: `Introduction to Drones: Take Flight! (K-2nd)`,
    legacyPath: `/product/introduction-to-drones-take-flight-k-2nd/`,
    body: [
      `Go To Schedule`,
      `Course Description`,
      `Students will be introduced to drones. Students will experience how flight occurs and what is necessary for animals and objects to take flight.`,
      `Level One`,
      `Students will explore gravity and the effects it has on objects and actions`,
      `Students learn about the main principles of flight.`,
      `Students will be able to explain the cause and effect of air pressure on movement.`,
      `Students will explore the concept of push and pull. They will focus on how the two interact and relate to flight`,
      `Students will be introduced to the drone. Students will learn the importance of safety and proper handling of drones.`,
      `Level Two`,
      `Students will further investigate push and pull. They will also experiment with the cause and effect that different forces have on the Scoot drone.`,
      `Students will read/hear a short story about a problem in the future. They will work together to design a concept for a drone that delivers pizzas. They will draw a model and generate ideas.`,
      `Students will explore flight. Students will identify the parts of a plane and create a flying model.`,
      `Students will compare how bees and drones fly. Students will fly a Scoot drone to simulate a bee’s waggle dance.`,
      `Students will select a photography subject and fly a drone to take a bird’s eye view of the subject. The art lesson will focus on perspective drawing, where you will create a drawing of the subject based on the photograph and overhead view.`,
      `Standards Supported in Level I & II`,
      `NGSS`,
      `K-PS2-1 Plan and conduct an investigation to compare the effects of different strengths or different directions of pushes and pulls on the motion of an object.`,
      `K-PS2-2 Pushes and pulls can have different strengths and directions.`,
      `K-PS2-2. Analyze data to determine if a design solution works as intended to change the speed or direction of an object with a push or a pull.`,
      `1-LS1-1 Use materials to design a solution to a human problem by mimicking how plants and/or animals use their external parts to help them survive, grow, and meet their needs.`,
      `2-PS1-2 Simple tests can be designed to gather evidence to support or refute student ideas about causes.`,
      `2-PS1-4 Cause and Effect events have causes that generate observable patterns.`,
      `Schedule`,
      `Program Date Time Level`,
      `Drones: K-2 Week 1 Saturday, November 13, 2021 10am-11am Level 1`,
      `Drones: K-2 Week 2 Saturday, November 20, 2021 10am-11am Level 1`,
      `Drones: K-2 Week 3 Saturday, December 4, 2021 10am-11am Level 1`,
      `Drones: K-2 Week 4 Saturday, December 11, 2021 10am-11am Level 1`,
      `Drones: K-2 Week 5 Saturday, December 18, 2021 10am-11am Level 1`,
      `Drones: K-2 Week 6 Saturday, January 8, 2022 10am-11am Level 1`,
      `Drones: K-2 Week 7 Saturday, January 15, 2022 10am-11am Level 2`,
      `Drones: K-2 Week 8 Saturday, January 22, 2022 10am-11am Level 2`,
      `Drones: K-2 Week 9 Saturday, January 29, 2022 10am-11am Level 2`,
      `Drones: K-2 Week 10 Saturday, February 5, 2022 10am-11am Level 2`,
      `Drones: K-2 Week 11 Saturday, February 12, 2022 10am-11am Level 2`,
      `Drones: K-2 Week 12 Saturday, February 19, 2022 10am-11am Level 2`,
    ],
  },
  {
    slug: `parent-night-out`,
    name: `Parent Night Out!`,
    group: `STEAM Programs`,
    grades: null,
    summary: `Details Parents Night Out in Holly Springs STEM Fun for Kids, A Night Off for You Looking for a safe, structured, and genuinely fun night for your child while you enjoy a well-earned evening out? At Resource Room Learning Center, our Parents Night Out program in Holly Springs is more than babysitting—it’s an engaging STEM […]`,
    price: null,
    image: `/images/courses/parent-night-out.jpg`,
    imageAlt: `Parent Night Out!`,
    legacyPath: `/product/parent-night-out/`,
    body: [
      `Details`,
      `Parents Night Out in Holly Springs`,
      `STEM Fun for Kids, A Night Off for You`,
      `Looking for a safe, structured, and genuinely fun night for your child while you enjoy a well-earned evening out?`,
      `At Resource Room Learning Center, our Parents Night Out program in Holly Springs is more than babysitting—it’s an engaging STEM experience designed to keep kids active, social, and learning.`,
      `What Makes Our Parent Night Different`,
      `This is not just free play.`,
      `Every Parents Night Out is built around:`,
      `Hands-on STEM activities`,
      `Creative building challenges`,
      `Structured group games`,
      `High-energy, supervised fun`,
      `Kids are engaged the entire time`,
      `Parents get peace of mind`,
      `Themes: Fizzy, Bubbly Fun`,
      `Your child will dive into a night of:`,
      `LEGO building challenges`,
      `Hands-on science experiments (fizz, bubbles, safe “explosions”)`,
      `Team-based games and problem-solving activities`,
      `Pizza, snacks, and water included`,
      `It’s learning disguised as fun—and kids love it`,
      `Why Parents Choose Resource Room`,
      `We are not a drop-off play center.`,
      `We are educators.`,
      `That means:`,
      `Activities are intentional and structured`,
      `Staff are experienced educators`,
      `Students are engaged, supported, and supervised`,
      `Your child is not just watched—they are actively learning and participating`,
      `Who This Is Perfect For`,
      `Kids who enjoy building, experimenting, and creating`,
      `Students who need structured, engaging environments`,
      `Children who thrive with hands-on learning`,
      `Kids who want to have fun while making friends`,
      `Parents Night Out Near You (Holly Springs, NC)`,
      `Resource Room provides a trusted, local option for parents looking for kids night out programs, STEM activities, and safe evening childcare alternatives.`,
      `Spots Are Limited`,
      `We intentionally keep groups small to maintain quality and engagement.`,
      `Reserve your spot today before we fill up`,
      `Ready to Book?`,
      `Give yourself the night off – your child will thank you for it.`,
      `Schedule`,
      `Date`,
      `Fall Dates TBA`,
    ],
  },
  {
    slug: `scratch-coding`,
    name: `Scratch Coding`,
    group: `STEAM Programs`,
    grades: null,
    summary: `Scratch is a coding community for children. The coding language comes with simple visual interface that allows children to create digital stories, games, cards, and animations. Classes coming February 2023`,
    price: { low: 249, high: 249 },
    image: `/images/courses/scratch-coding.jpg`,
    imageAlt: `coding`,
    legacyPath: `/product/scratch-coding/`,
    body: [
      `Scratch is a coding community for children. The coding language comes with simple visual interface that allows children to create digital stories, games, cards, and animations.`,
      `Scratch fosters critical thinking and problem solving skills, creative thinking, expression, and teamwork skills. Come learn the basics of coding through our scratch coding course. Scratch offers the basics with drag and drop coding. Your child will learn how to make games like Pong, Flappy Bird, Fruit Ninja, and more!`,
    ],
  },
  {
    slug: `steam-programs-at-resource-room-nc`,
    name: `STEAM Programs at Resource Room NC`,
    group: `STEAM Programs`,
    grades: null,
    summary: `Resource Room provides a comprehensive STEAM program offering that scaffold accordingly to build on student knowledge and engagement. We offer a variety of Curriculum Bases STEAM classes focused on promoting learning, team building, and an in-depth exploration of various academic disciplines.`,
    price: null,
    image: `/images/courses/steam-programs-at-resource-room-nc.jpg`,
    imageAlt: `STEAM Programs at Resource Room NC`,
    legacyPath: `/product/steam-programs-at-resource-room-nc/`,
    body: [
      `Discover the Wonders of STEAM at Resource Room NC! 🚀`,
      `At Resource Room, we bring the exciting world of STEAM (Science, Technology, Engineering, Arts, and Mathematics) to life for young minds! Our comprehensive program is specially designed to build on your child’s curiosity and knowledge, step by step. Join us for an adventure in learning, teamwork, and deep exploration across various academic disciplines.`,
      `Developed by licensed teachers, our curriculum promises a fun and engaging educational journey. It’s structured to inspire and foster a love for learning in every child.`,
      `What Exciting STEAM Programs Do We Offer?`,
      `Drones: The Sky’s the Limit! 🚁`,
      `Grades K-8 will marvel at the science of flight, from basic principles to advanced drone technology. Watch your child’s imagination take flight as they learn about automated flight, drone delivery, and more!`,
      `Robotics: Building the Future! 🤖`,
      `Ideal for Grades K-8, our Robotics program introduces the basics of coding and automation. Your child will learn how robots work and even try their hand at programming!`,
      `3-D Printing: Bringing Ideas to Life! 🖨️`,
      `Available for Grades 3-8, this program explores the fascinating world of 3-D printing. Watch as your child’s creations come to life, learning about programming, design, and much more.`,
      `Lego Robotics and Exploration: Construct, Create, Collaborate! 🧱`,
      `Our Lego Education Courses are all about hands-on learning and teamwork. It’s a perfect blend of science, engineering, and creativity for all ages.`,
      `Why Choose Resource Room for STEAM Learning?`,
      `Resource Room is more than just a learning center – it’s a hub of “funducational” experiences! We blend interactive, foundational, and advanced concepts in Science and Math to make learning accessible and exciting. Our STEAM programs emphasize skills like teamwork, communication, and community planning – essential for both academic and professional growth. STEAM education at Resource Room is:`,
      `Inclusive for all types of learners`,
      `A great way to promote socialization`,
      `Rich with real-world applications and concepts`,
      `Hands-On Learning:`,
      `Hands-on Science Experiments: Get ready for fun and discovery with activities like fluffy slime, volcanic eruptions, and elephant toothpaste!`,
      `Creative LEGO Building Challenges: Imagination meets engineering as campers build everything from bridges to roller coasters.`,
      `Artistic Crafts and Self-Expression: Campers will craft, design, and express themselves in countless creative ways.`,
      `Outdoor Adventures and Nature Exploration: We believe in the power of outdoor learning – from nature walks to outdoor games, there’s always something new to explore.`,
      `Coding Challenges and Digital Literacy: Dive into the digital world with coding adventures, from programming LEGO® robots to creating animated stories.`,
      `Join us at Resource Room NC for a STEAM experience your child will never forget – where learning, fun, and imagination come together to create something extraordinary! 🌟`,
    ],
  },
  {
    slug: `educational-workshops`,
    name: `Educational Workshops`,
    group: `Workshops`,
    grades: null,
    summary: `At Resource Room Learning Center, we believe in empowering students with the tools they need to succeed both academically and personally. Our series of educational workshops are designed to provide deep insights and practical skills in various areas of a student’s educational journey. Join us for these engaging sessions led by experienced speakers and experts in the field!`,
    price: { low: 0, high: 0 },
    image: null,
    imageAlt: `Educational Workshops`,
    legacyPath: `/product/educational-workshops/`,
    body: [
      `Educational Workshops at Resource Room Learning Center`,
      `We are dedicated to supporting your child’s academic and personal growth through our comprehensive series of workshops. These sessions are crafted to tackle key challenges and milestones in a student’s educational journey, offering expert insights and practical strategies for success.`,
      `Why Attend Our Workshops?`,
      `For Students: Our workshops provide students with the tools and knowledge they need to excel in their studies and beyond. Each session is designed to enhance understanding, boost confidence, and develop essential academic and life skills.`,
      `For Parents: Understanding your role in your child’s education can be transformative. Our workshops offer valuable perspectives and strategies to help you effectively support your child’s learning and development. Engage with experts to learn how you can foster a conducive learning environment at home, reinforcing the lessons and values we teach.`,
      `Workshop Topics Include:`,
      `1. Mastering Math Fundamentals`,
      `2. Effective Study Habits`,
      `3. Navigating College Admissions`,
      `4. Science Simplified`,
      `5. Reading and Writing Excellence`,
      `6. Stress Management and Mental Wellness`,
      `7. Executive Functioning Skills`,
      `Meet Our Speakers`,
      `Our workshops are led by a team of experienced educators, counselors, and industry experts who bring a wealth of knowledge and enthusiasm to each session. They are passionate about making a difference in the lives of our students and are eager to share their expertise.`,
      `Join Us`,
      `Embrace the opportunity to enhance your child’s education and personal development. Our workshops are a stepping stone towards academic excellence and a well-rounded education. Contact us today to learn more about our upcoming sessions and how to register.`,
      `Upcoming Workshop`,
      `Friday, June 7, 2024`,
      `From 5:30 PM- 7:00 PM with Claudia Rickard`,
      `Why Attend?`,
      `Tackle common childhood issues such as anxiety, fears, and disruptive behavior.`,
      `Enhance your child’s capacity to manage daily activities and challenges.`,
      `Foster a nurturing environment that promotes development and well-being.`,
      `Master a 100% safe and non-intrusive technique that nurtures inner strength and confidence.`,
      `Who Should Attend? Parents seeking effective, compassionate methods to help their children thrive in today’s world—whether dealing with external stresses or internal struggles.`,
      `Key Benefits of The SleepTalk® for Children:`,
      `✔️ Encourages positive behavior and emotional stability.`,
      `✔️ Supports developmental and behavioral advancement.`,
      `✔️ Provides lifelong tools for confidence and resilience.`,
      `✔️ Safe for children of all ages, from infants to teens.`,
      `Take the first step towards transforming your child’s life. Secure your seat now and be the positive change in your child’s developmental journey!`,
      `👉 Register and learn more about empowering your child with SleepTalk®!`,
    ],
  },
];

export function getCourse(slug: string): Course | undefined {
  return courses.find((course) => course.slug === slug);
}

export const courseGroups = [...new Set(courses.map((course) => course.group))];

export function coursesInGroup(group: string): Course[] {
  return courses.filter((course) => course.group === group);
}

/**
 * WooCommerce product-tag archives. Thin, near-duplicate pages with no
 * equivalent here, so they fold back into the catalog rather than 404.
 */
export const legacyProductTagPaths: string[] = [
  `/product-tag/3d-design`,
  `/product-tag/3d-printing`,
  `/product-tag/aba-support`,
  `/product-tag/act`,
  `/product-tag/act-test-prep`,
  `/product-tag/arts-and-crafts`,
  `/product-tag/autism`,
  `/product-tag/autism-support`,
  `/product-tag/beginner-robotics`,
  `/product-tag/behavior-support`,
  `/product-tag/child-development`,
  `/product-tag/coding`,
  `/product-tag/college-exams`,
  `/product-tag/digital-media`,
  `/product-tag/drones`,
  `/product-tag/education`,
  `/product-tag/executive-functioning`,
  `/product-tag/flight`,
  `/product-tag/gaming-education`,
  `/product-tag/hands-on-activities`,
  `/product-tag/homeschool`,
  `/product-tag/homework-help`,
  `/product-tag/learning`,
  `/product-tag/lego`,
  `/product-tag/lego-robotics`,
  `/product-tag/legos`,
  `/product-tag/math`,
  `/product-tag/minecraft`,
  `/product-tag/minecraft-education`,
  `/product-tag/minecraft-engineering`,
  `/product-tag/minecraft-learning`,
  `/product-tag/neurodiverse-learners`,
  `/product-tag/pathways-academy`,
  `/product-tag/private-tutoring`,
  `/product-tag/roblox`,
  `/product-tag/roblox-stem`,
  `/product-tag/robotics`,
  `/product-tag/robots`,
  `/product-tag/sat`,
  `/product-tag/sat-test-prep`,
  `/product-tag/science`,
  `/product-tag/special-education-support`,
  `/product-tag/steam`,
  `/product-tag/stem`,
  `/product-tag/structured-playtime`,
  `/product-tag/structured-story-time`,
  `/product-tag/summer-programs`,
  `/product-tag/teacher-workday`,
  `/product-tag/technology`,
  `/product-tag/test-prep`,
  `/product-tag/tinkercad`,
  `/product-tag/track-out`,
  `/product-tag/tutor`,
  `/product-tag/tutoring`,
  `/product-tag/tutoring-and-aba`,
  `/product-tag/virtual-tutor`,
  `/product-tag/workshop`,
];
